### ISSUE TITLE
Working with fonts

### ISSUE THREAD

**Issue by tinenmi** [dreambottle/R11-psp-english#1]
I want to change fonts to reduce printed text size. It's also can be helped for localizations.
I've a font working tool for desktop version of Remember11, but file formats doesn't match. Please, write font change tools for PSP and I'll test text out in entire game.

**Comment by dreambottle** [comment]
Hi and thanks for interest in this project!

I did some research on how to properly extract the fonts and started writing a script to extract it to PNG, but it's unfinished yet. Hopefully I will have some time to work on it in a few weeks.

Note, it is undesirable to change the font height because the same font is used everywhere in the game and it may become ugly or unreadable in some places.

Besides, I also found out that the line height in the text boxes was hardcoded into the game and changing the font height does not automatically make more lines fit into the text box.

**Comment by tinenmi** [comment]
I know many people interesting in your project.   I wlould reduce font height by 2 pixel to increase paddings. And width of some characters of my language can be reduced by half.

**Comment by tinenmi** [comment]
May I help you with coding?

**Comment by dreambottle** [comment]
I've recently pushed a script that repacks the font with the left and right borders of the glyphs reduced by 1px. This simple hack notably improves readability and increases the amount of glyphs per line to ~45.

The complete font extraction is under way.

**Comment by tinenmi** [comment]
Thanks. It's good news.

**Comment by tinenmi** [comment]
Thanks. But font extracting doesn't work anymore and during trowing error writes that pngMapsPath0 doesn't exist.

**Comment by dreambottle** [comment]
@tinenmi Fixed in 9e00cfc. You were probably trying to repack the font. Note that the input PNG files must be greyscale with the bitdepth of 2 (only 4 shades of grey available)

**Comment by dreambottle** [comment]
Closing, as the functionality has been implemented
