### ISSUE TITLE
Alternate ways to patch the game?

### ISSUE THREAD

**Issue by Lycan911** [dreambottle/R11-psp-english#4]
Any way you could add an alternate way to patch the game? Something like [xDelta](http://www.romhacking.net/utilities/598/) for example? The current method is way too confusing for an average user IMO.

**Comment by dreambottle** [comment]
Yes, this sounds doable.
The reason why I never did it is because the project is in a beta phase, and bugs and crashes are still expected, especially in the Tips section. The story is now fully playable though, so I'll check out

**Comment by Lycan911** [comment]
Nice, thanks.

**Comment by RetroGameTalk** [comment]
I could pull it off it there were step by step instructions but with the current ones seems impossible.

**Comment by dreambottle** [comment]
Pardon me for keeping this issue quiet, as I didn't have much time to look at this issue until the last week. Here's the current status of it:

I tried xdelta3 to make a patch for the iso image, but the patch was taking about 80% size of the original file, so I thought this wasn't the right way to go.

What I currently want to do is to create xdelta patches for individual files, compile a minimal set of tools, required to extract and pack the game resources, and write a simple gui or even a console patcher which does all the steps in the right order.

All of this is done, except the last step - the patcher which would automate the process. If you're interested, I could release the bundle as is and write a step-by step guide of what to do, so that you can try it now.

What do you think?

**Comment by RetroGameTalk** [comment]
Sure if you can please i'd appreciate it.

**Comment by Lycan911** [comment]
As soon as you write a guide, I'm in.

**Comment by dreambottle** [comment]
I started writing a guide, but somehow ended up with a .bat file 😄 

The very first in the world release of the Remember11 English patch for PSP is now available for download here:
https://github.com/dreambottle/R11-psp-english/releases/tag/1.0-beta

**Comment by Lycan911** [comment]
Works great on my PSP! http://imgur.com/a/kLugT
Thanks for your hard work, I'll report any issues I come across!

**Comment by dreambottle** [comment]
Closing this, as the patcher is now available.
